/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as HomenagensRouteImport } from './routes/homenagens'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AcoesRouteImport } from './routes/acoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscritosIndexRouteImport } from './routes/escritos.index'
import { Route as EscritosSlugRouteImport } from './routes/escritos.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const HomenagensRoute = HomenagensRouteImport.update({
  id: '/homenagens',
  path: '/homenagens',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoesRoute = AcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritosIndexRoute = EscritosIndexRouteImport.update({
  id: '/escritos/',
  path: '/escritos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritosSlugRoute = EscritosSlugRouteImport.update({
  id: '/escritos/$slug',
  path: '/escritos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/homenagens': typeof HomenagensRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/escritos/$slug': typeof EscritosSlugRoute
  '/escritos/': typeof EscritosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/homenagens': typeof HomenagensRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/escritos/$slug': typeof EscritosSlugRoute
  '/escritos': typeof EscritosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoes': typeof AcoesRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/homenagens': typeof HomenagensRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/quem-somos': typeof QuemSomosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/escritos/$slug': typeof EscritosSlugRoute
  '/escritos/': typeof EscritosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoes'
    | '/contato'
    | '/depoimentos'
    | '/galeria'
    | '/historia'
    | '/homenagens'
    | '/linha-do-tempo'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/escritos/$slug'
    | '/escritos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoes'
    | '/contato'
    | '/depoimentos'
    | '/galeria'
    | '/historia'
    | '/homenagens'
    | '/linha-do-tempo'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/escritos/$slug'
    | '/escritos'
  id:
    | '__root__'
    | '/'
    | '/acoes'
    | '/contato'
    | '/depoimentos'
    | '/galeria'
    | '/historia'
    | '/homenagens'
    | '/linha-do-tempo'
    | '/quem-somos'
    | '/sitemap.xml'
    | '/escritos/$slug'
    | '/escritos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoesRoute: typeof AcoesRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  GaleriaRoute: typeof GaleriaRoute
  HistoriaRoute: typeof HistoriaRoute
  HomenagensRoute: typeof HomenagensRoute
  LinhaDoTempoRoute: typeof LinhaDoTempoRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EscritosSlugRoute: typeof EscritosSlugRoute
  EscritosIndexRoute: typeof EscritosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homenagens': {
      id: '/homenagens'
      path: '/homenagens'
      fullPath: '/homenagens'
      preLoaderRoute: typeof HomenagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoes': {
      id: '/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AcoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritos/': {
      id: '/escritos/'
      path: '/escritos'
      fullPath: '/escritos/'
      preLoaderRoute: typeof EscritosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritos/$slug': {
      id: '/escritos/$slug'
      path: '/escritos/$slug'
      fullPath: '/escritos/$slug'
      preLoaderRoute: typeof EscritosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoesRoute: AcoesRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  GaleriaRoute: GaleriaRoute,
  HistoriaRoute: HistoriaRoute,
  HomenagensRoute: HomenagensRoute,
  LinhaDoTempoRoute: LinhaDoTempoRoute,
  QuemSomosRoute: QuemSomosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EscritosSlugRoute: EscritosSlugRoute,
  EscritosIndexRoute: EscritosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
